### ISSUE TITLE
Fails to parse [[multientry]] sections

### ISSUE THREAD

**Issue by TheLQ** [asafh/jtoml#4]
Attempting to parse the following file

```
[[servers]]
name = "server1"

[[servers]]
name = "server2"
```

Throws this during parsing

```
Exception in thread "main" io.ous.jtoml.ParseException: Cannot overwrite key [servers]
    at io.ous.jtoml.impl.Parser.onKeygroup(Parser.java:118)
    at io.ous.jtoml.impl.Parser.onLine(Parser.java:58)
    at io.ous.jtoml.impl.Parser.parse(Parser.java:43)
    at io.ous.jtoml.JToml.parse(JToml.java:33)
    at io.ous.jtoml.JToml.parse(JToml.java:21)
    at io.ous.jtoml.JToml.parse(JToml.java:18)
    at org.thelq.pircbotx.TomlTest.main(TomlTest.java:19)
```

This is valid TOML according to the toml standard readme: https://github.com/toml-lang/toml

**Comment by asafh** [comment]
Fixed in #7, please use version 2.0.0 deployed to Maven.
