### ISSUE TITLE
Fails to parse single quotes

### ISSUE THREAD

**Issue by TheLQ** [asafh/jtoml#5]
The following file

```
name = 'bob'
```

Fails with this exception

```
Exception in thread "main" io.ous.jtoml.ParseException: Could not identify value 'bob'
    at io.ous.jtoml.impl.ConsumableType.readValue(ConsumableType.java:38)
    at io.ous.jtoml.impl.Parser.onAssignment(Parser.java:96)
    at io.ous.jtoml.impl.Parser.onLine(Parser.java:61)
    at io.ous.jtoml.impl.Parser.parse(Parser.java:43)
    at io.ous.jtoml.JToml.parse(JToml.java:33)
    at io.ous.jtoml.JToml.parse(JToml.java:21)
    at io.ous.jtoml.JToml.parse(JToml.java:18)
    at org.thelq.pircbotx.TomlTest.main(TomlTest.java:19)
```

**Comment by asafh** [comment]
Fixed in #7, please use version 2.0.0 deployed to Maven.
